//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmFieldPlantHarvestData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FarmFieldPlantHarvestData()
        {
            this.FarmFieldPlantHarvestDataDetails = new HashSet<FarmFieldPlantHarvestDataDetail>();
        }
    
        public int FarmFieldPlantHarvestDataID { get; set; }
        public int FarmFieldPlantID { get; set; }
        public System.DateTime HarvestDate { get; set; }
        public string WeightTicketNumber { get; set; }
        public Nullable<double> TotalPoundsIn { get; set; }
        public Nullable<int> TotalContainers { get; set; }
        public Nullable<double> AverageWeightPerContainer { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmFieldPlantHarvestDataDetail> FarmFieldPlantHarvestDataDetails { get; set; }
        public virtual FarmFieldPlant FarmFieldPlant { get; set; }
    }
}
