//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> QuantityPerPallet { get; set; }
        public string PalletType { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public string Size { get; set; }
        public string Brand { get; set; }
        public string Grade { get; set; }
        public string Color { get; set; }
        public string FieldNo { get; set; }
        public string LotNo { get; set; }
        public string WarehouseLocation { get; set; }
        public string SKU { get; set; }
        public string productBarCode { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RetailUPCCode { get; set; }
        public Nullable<decimal> ProductWeight { get; set; }
        public string VendorUCC { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
