//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTIHeader
    {
        public int PTISerialID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int FarmFieldPlantID { get; set; }
        public int ProductID { get; set; }
        public int CreatedByID { get; set; }
    }
}
