//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecurityLevel()
        {
            this.Users = new HashSet<User>();
        }
    
        public int SecurityLevelID { get; set; }
        public string SecurityLevelName { get; set; }
        public int UserTypeID { get; set; }
        public bool PageEdit { get; set; }
        public bool PageView { get; set; }
        public bool PageDelete { get; set; }
        public Nullable<int> PageId { get; set; }
    
        public virtual PageDetail PageDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
