//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int SupplyID { get; set; }
        public string SupplyCode { get; set; }
        public string Description { get; set; }
        public string SupplyType { get; set; }
        public string UnitOfMeasure { get; set; }
        public string Comment { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> NotificationLevel { get; set; }
    }
}
