//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmFieldPlant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FarmFieldPlant()
        {
            this.FarmFieldPlantHarvestDatas = new HashSet<FarmFieldPlantHarvestData>();
        }
    
        public int FarmFieldPlantID { get; set; }
        public int FarmFieldID { get; set; }
        public int CategoryID { get; set; }
        public string ProduceIDNumber { get; set; }
        public System.DateTime DatePlanted { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> ScheduledHarvestDate { get; set; }
        public Nullable<double> TotalPoundsHarvested { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmFieldPlantHarvestData> FarmFieldPlantHarvestDatas { get; set; }
        public virtual FarmField FarmField { get; set; }
    }
}
