//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models.DbEntity
{
    using System;
    
    public partial class USP_User_Login_Result1
    {
        public int UserID { get; set; }
        public int UserTypeID { get; set; }
        public int SecurityLevelID { get; set; }
        public string SecurityLevelName { get; set; }
        public string UserTypeName { get; set; }
        public int PageId { get; set; }
    }
}
